version: "3.9"
services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./Backend:/app

  frontend:
    build: ./FrontEnd
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: